Repository CampingOn/CampingOn-BE, pull requests merged in 2024-11, with the labels that each got.

#6 feat: #2 User Entity & Repository 구현
  src/main/java/site/campingon/campingon/user/entity/Role.java
  src/main/java/site/campingon/campingon/user/entity/User.java
  src/main/java/site/campingon/campingon/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: feature

#9 Feat/#7 camp
  src/main/java/site/campingon/campingon/common/public_data/PublicDataConstants.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/resources/application.yml
Labels: feature

#19 [FEAT] Camp 관련 Entity들 생성
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/entity/CampImage.java
  src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
  src/main/java/site/campingon/campingon/camp/entity/CampKeyword.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
Labels: feature

#18 Feat/#4 user oauth 2.0 구글 로그인 구현
  build.gradle
  src/main/java/site/campingon/campingon/common/config/AppConfig.java
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/config/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/config/oauth/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/common/config/oauth/TestController.java
  src/main/java/site/campingon/campingon/common/config/oauth/dto/OAuth2UserDto.java
  src/main/java/site/campingon/campingon/common/config/oauth/dto/provider/GoogleResponseDto.java
  src/main/java/site/campingon/campingon/common/config/oauth/dto/provider/OAuth2ResponseDto.java
  src/main/java/site/campingon/campingon/user/entity/User.java
  src/main/java/site/campingon/campingon/user/repository/CampRepository.java
  src/main/java/site/campingon/campingon/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feature

#27 Feat/#26 공공데이터 DB저장
  src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampImageRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampKeywordRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingRequestDto.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingResponseDto.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#46 Feat/#44 - 1주차 코드리뷰 피드백 반영
  src/main/java/site/campingon/campingon/common/public_data/GoCampingPath.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingParsedResponseDto.java
  src/main/java/site/campingon/campingon/common/public_data/mapper/GoCampingMapper.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: enhancement

#48 Feat/#37 전역예외처리 설계 완료
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/exception/ErrorResponse.java
  src/main/java/site/campingon/campingon/common/exception/GlobalException.java
  src/main/java/site/campingon/campingon/common/exception/GlobalExceptionHandler.java
Labels: feature

#52 Feat/#43 코드리뷰 수정 + 스크럼 내용 반영 + API명세서 수정
  src/main/java/site/campingon/campingon/bookmark/controller/CampController.java
  src/main/java/site/campingon/campingon/bookmark/entity/BookMark.java
  src/main/java/site/campingon/campingon/bookmark/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/bookmark/repository/BookMarkRepository.java
  src/main/java/site/campingon/campingon/bookmark/service/CampService.java
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/like/controller/CampController.java
  src/main/java/site/campingon/campingon/like/dto/CampDto.java
  src/main/java/site/campingon/campingon/like/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/like/service/CampService.java
Labels: enhancement

#69 Feat/#68 CampSiteAdminController 작성
  src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
  src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
  src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
Labels: enhancement, feature

#67 Feat/#66 CampAdminController 작성
  src/main/java/site/campingon/campingon/camp/controller/CampAdminController.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampCreateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampUpdateRequestDto.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
Labels: enhancement, feature

#62 Feat/#53 Bookmark 도메인 서비스 분리 및 구축
  src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
  src/main/java/site/campingon/campingon/bookmark/controller/CampController.java
  src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
  src/main/java/site/campingon/campingon/bookmark/repository/BookmarkRepository.java
  src/main/java/site/campingon/campingon/bookmark/service/BookmarkService.java
  src/main/java/site/campingon/campingon/bookmark/service/CampService.java
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#63 Feat/#31 AOP 로깅 적용
  src/main/java/site/campingon/campingon/common/aop/GlobalLoggingAspect.java
  src/main/resources/application.yml
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: feature

#74 Feat/#65 Camp, CampSite 엔티티와 GoCampingService 수정
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampInduty.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/entity/Induty.java
  src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
  src/main/java/site/campingon/campingon/common/converter/IndutyConverter.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingParsedResponseDto.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#75 Feat/#70 지역(시/도) 정보와 키워드를 바탕으로한 캠핑장 검색기능
  src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
Labels: feature

#76 Feat/#71 JWT 토큰 이용 로그인 구현
  src/main/java/site/campingon/campingon/common/config/oauth/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/jwt/JwtAuthenticationFilter.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshToken.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshTokenService.java
  src/main/java/site/campingon/campingon/common/util/CookieUtil.java
  src/main/java/site/campingon/campingon/user/controller/UserAuthController.java
  src/main/java/site/campingon/campingon/user/controller/UserController.java
  src/main/java/site/campingon/campingon/user/entity/Role.java
  src/main/java/site/campingon/campingon/user/mapper/UserMapper.java
  src/main/java/site/campingon/campingon/user/service/UserAuthService.java
  src/main/java/site/campingon/campingon/user/service/UserService.java
Labels: feature, subtask

#77 Feat/#64 CampImage DB 저장 및 커스텀 예외처리
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/common/converter/IndutyConverter.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingImageDto.java
  src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingImageParsedResponseDto.java
  src/main/java/site/campingon/campingon/common/public_data/mapper/GoCampingMapper.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#81 Feat/#78 공공데이터 생성일, 수정일 저장
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampInduty.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#82 Feat/#45 oauth 유저 로그인 성공, 실패 핸들러 생성
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/config/oauth/TestController.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/exception/GlobalExceptionHandler.java
  src/main/java/site/campingon/campingon/common/exception/OAuthException.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2FailureHandler.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuthSuccessHandler.java
  src/main/java/site/campingon/campingon/common/oauth/TestController.java
  src/main/java/site/campingon/campingon/common/oauth/dto/OAuth2UserDto.java
  src/main/java/site/campingon/campingon/common/oauth/dto/provider/GoogleResponseDto.java
  src/main/java/site/campingon/campingon/common/oauth/dto/provider/OAuth2ResponseDto.java
  src/main/java/site/campingon/campingon/user/entity/User.java
  src/main/resources/logback-spring.xml
Labels: feature

#86 Feat/#73 s3 서비스 설정 및 환경 구축
  build.gradle
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/s3bucket/Dto/S3BucketRemoveRequestDto.java
  src/main/java/site/campingon/campingon/s3bucket/config/S3Config.java
  src/main/java/site/campingon/campingon/s3bucket/controller/S3BucketController.java
  src/main/java/site/campingon/campingon/s3bucket/service/S3BucketService.java
  src/main/resources/application-s3Bucket.yml
  src/main/resources/application.yml
Labels: feature

#88 Feat/#80 Camp ID가 가지고 있는 CampImage 저장 구현
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#92 Feat/#45 oauth 유저 탈퇴 시 구글 api 연동 해제
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/oauth/TestController.java
  src/main/java/site/campingon/campingon/common/oauth/dto/provider/GoogleResponseDto.java
  src/main/java/site/campingon/campingon/common/oauth/dto/provider/OAuth2ResponseDto.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuth2FailureHandler.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
Labels: feature

#95 Feat/#84 캠핑장서비스 관련 단위 테스트
  src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/s3bucket/Dto/S3BucketRemoveRequestDto.java
  src/main/java/site/campingon/campingon/s3bucket/controller/S3BucketController.java
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
Labels: enhancement

#100 Feat/#96 reservation 예약 필수 클래스 생성
  src/main/java/site/campingon/campingon/common/entity/BaseEntity.java
  src/main/java/site/campingon/campingon/common/oauth/TestController.java
  src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/reservation/controller/CampController.java
  src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
  src/main/java/site/campingon/campingon/reservation/dto/CampDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreatedRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/entity/Camp.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
  src/main/java/site/campingon/campingon/reservation/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/reservation/repository/CampRepository.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/CampService.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
  src/main/java/site/campingon/campingon/user/entity/User.java
Labels: feature

#106 Feat: #102 JWT token 저장 방식 변경
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/site/campingon/campingon/user/controller/UserAuthController.java
  src/main/java/site/campingon/campingon/user/dto/UserResponseDto.java
  src/main/resources/application-dev.yml
Labels: feature, subtask

#103 Feat/#101 CampService 주요 메서드 별 실패 테스트, CampSite 목록 조회 테스트
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
Labels: enhancement

#105 Feat/#104 CampSite 수정 & 테스트 코드 추가
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampCreateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampUpdateRequestDto.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
  src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/review/controller/CampController.java
  src/main/java/site/campingon/campingon/review/entity/Camp.java
  src/main/java/site/campingon/campingon/review/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/review/repository/CampRepository.java
  src/main/java/site/campingon/campingon/review/service/CampService.java
  src/test/java/site/campingon/campingon/camp/repository/CampSiteRepositoryTest.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
Labels: enhancement, feature, subtask

#111 Feat/#110 CampSite 수정 & 테스트 코드 추가, 피드백 반영3
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
  src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
Labels: bug fix

#112 Feat/#89 공공데이터 관련 테스트 코드작성
  src/main/java/site/campingon/campingon/common/config/RestTemplateConfig.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/test/java/site/campingon/campingon/common/public_data/service/GoCampingServiceTest.java
Labels: enhancement, feature

#113 Feat/#107 reservation 컨버터, 매퍼, dto 완료
  src/main/java/site/campingon/campingon/common/converter/ReservationStatusConverter.java
  src/main/java/site/campingon/campingon/common/entity/BaseEntity.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuth2FailureHandler.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCancelRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
Labels: feature

#121 Feat/#89 h2->mysql 이동, 스프링 스케줄러 추가
  build.gradle
  src/main/java/site/campingon/campingon/CampingOnBeApplication.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/resources/application.yml
Labels: bug, enhancement, feature

#118 Feat/#116 캠핑장에서 예약 가능한 캠핑지 목록 조회
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
Labels: feature, subtask

#128 Fix: #127 LazyInitializationException 해결
  src/main/java/site/campingon/campingon/user/entity/User.java
  src/main/java/site/campingon/campingon/user/entity/UserKeyword.java
Labels: bug fix

#132 refactor: 예약 비즈니스 로직에 @Transactional 추가
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
Labels: enhancement

#133 [Fix] CampAddr Point 타입 변경에 대한 CampServiceTest 수정
  build.gradle
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
Labels: enhancement, bug fix

#136 Feat: #135 User 관련 메서드 Custome Error Code 적용
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/user/service/UserService.java
Labels: enhancement

#134 Fix: #119 Point DB 저장 시 발생하는 Deserialize 문제 해결
  build.gradle
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/resources/application.yml
Labels: bug fix

#131 Feat/#130 리뷰 기능 구현 및 추천 토글 기능 추가
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/entity/CampImage.java
  src/main/java/site/campingon/campingon/camp/entity/CampInduty.java
  src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
  src/main/java/site/campingon/campingon/camp/entity/CampKeyword.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/dto/CampDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewCreateRequestDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewUpdateRequestDto.java
  src/main/java/site/campingon/campingon/review/entity/Review.java
  src/main/java/site/campingon/campingon/review/entity/ReviewImage.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewImageMapper.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
  src/main/java/site/campingon/campingon/review/repository/ReviewImageRepository.java
  src/main/java/site/campingon/campingon/review/repository/ReviewRepository.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
  src/test/java/site/campingon/campingon/review/service/ReviewServiceTest.java
Labels: enhancement, feature
