Repository CampingOn/CampingOn-BE, pull requests merged in 2024-12, with the labels that each got.

#143 Feat/#141 CampSiteService, ReviewService에 커스텀 예외 로직 추가
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
  src/test/java/site/campingon/campingon/review/service/ReviewServiceTest.java
Labels: enhancement

#151 Feat/#139 reservation 예약 가능한 캠프사이트 조회 api 통합
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCheckDateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/entity/CheckTime.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
  src/main/resources/application.yml
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement, feature

#148 Feat: #145 유저 관련 코드 리뷰 반영
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/jwt/CustomAccessDeniedHandler.java
  src/main/java/site/campingon/campingon/common/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/site/campingon/campingon/common/jwt/JwtAuthenticationFilter.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshToken.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshTokenService.java
  src/main/java/site/campingon/campingon/user/dto/UserSignInRequestDto.java
  src/main/java/site/campingon/campingon/user/dto/UserSignUpRequestDto.java
  src/main/java/site/campingon/campingon/user/dto/UserUpdateRequestDto.java
  src/main/java/site/campingon/campingon/user/service/UserAuthService.java
Labels: enhancement, feature

#152 Feat: #149 권한별 Path 설정
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/user/entity/User.java
Labels: feature

#160 fix : #159 camp, campInfo 조인시 조회가 안되는문제
  src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: bug fix

#164 Feat/#155 camp 캠프 도메인 코드 수정
  src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteReserveService.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCheckDateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement

#171 fix: SearchInfo의 campId Long타입 변경, SearchInfoController 엔드포인트 변경
  src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
  src/main/java/site/campingon/campingon/camp/entity/mongodb/SearchInfo.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
Labels: bug fix

#166 Feat/#165 CustomUserDetails name 필드 추가
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetailsService.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingProviderService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/user/service/UserAuthService.java
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
Labels: feature

#170 Fix/#167 camp, Camp_Info 생성 문제
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
  src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetailsService.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingProviderService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/user/service/UserAuthService.java
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
Labels: bug fix

#175 refactor: #174 캠프사이트 api url 수정
  src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
Labels: enhancement

#178 style : #176 maximum_people -> maximumPeople 변경
  src/main/java/site/campingon/campingon/camp/entity/Induty.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: subtask

#181 Refactor: #179 camp 피드백 반영 수정
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
  src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
  src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
Labels: enhancement

#185 Feat/#183 CampAddrDto, CampInfoDto 추가
  src/main/java/site/campingon/campingon/camp/dto/CampAddrDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampInfoDto.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
Labels: enhancement

#196 Feat: #195 백엔드 자동 배포 세팅
  .github/workflows/deploy.yml
Labels: feature

#184 Feat/#182 MongoDB 데이터 CampListResponseDto로 매핑
  src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
  src/main/java/site/campingon/campingon/camp/mapper/mongodb/SearchInfoMapper.java
  src/main/java/site/campingon/campingon/camp/repository/mongodb/SearchInfoRepository.java
  src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java
Labels: enhancement

#190 Refactor/#188 reservation 예약 생성 서비스 로직 수정, 컬럼명 변경
  src/main/java/site/campingon/campingon/camp/dto/CampAddrResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservedCampSiteIdListResponseDto.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
  src/main/java/site/campingon/campingon/reservation/utils/ReservationValidate.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement, bug fix

#192 feat : #191 캠핑장인기목록 조회 수정
  src/main/java/site/campingon/campingon/camp/controller/CampController.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java
Labels: feature

#194 Feat/#193 리뷰 이미지 파일 유무에 따른 차이 수정, 이미지 파일 검증 추가
  src/main/java/site/campingon/campingon/camp/mapper/mongodb/SearchInfoMapper.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/s3bucket/controller/S3BucketController.java
  src/main/java/site/campingon/campingon/common/s3bucket/service/S3BucketService.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/dto/ReviewCreateRequestDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewUpdateRequestDto.java
  src/main/java/site/campingon/campingon/review/entity/Review.java
  src/main/java/site/campingon/campingon/review/entity/ReviewImage.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
  src/main/java/site/campingon/campingon/review/repository/ReviewRepository.java
  src/main/java/site/campingon/campingon/review/schedule/ReviewScheduler.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: feature

#207 Fix: #206 Entry point withelist 추가
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/common/jwt/CustomAccessDeniedHandler.java
  src/main/java/site/campingon/campingon/common/jwt/CustomAuthenticationEntryPoint.java
Labels: bug fix

#210 Fix/#209 찜기능 컨트롤러 수정
  src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
Labels: bug fix

#212 Feat: #211 Google Oauth 로그인 수정
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/resources/application-prod.yml
Labels: feature

#214 Fix/#213 CampMapper에 위도, 경도 추가
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
Labels: enhancement

#226 fix: 예약리스트 조회 page 요청 허용
  src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
  src/main/resources/application.yml
Labels: bug fix

#217 Feat/#208 Altas Search 적용(자동완성 제외)
  build.gradle
  src/main/java/site/campingon/campingon/CampingOnBeApplication.java
  src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
  src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
  src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
  src/main/java/site/campingon/campingon/camp/repository/mongodb/MongoSearchClient.java
  src/main/java/site/campingon/campingon/camp/repository/mongodb/SearchInfoRepository.java
  src/main/java/site/campingon/campingon/camp/repository/mongodb/TestSearchInfoRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
Labels: feature

#223 feat: #221 다가오는 예약 조회 api 구현
  src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
Labels: feature

#244 Feat: #229 docker 사용 자동 배포
  .github/workflows/deploy.yml
  .github/workflows/docker-deploy.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement, feature

#238 Fix/#235스케줄러에서 이미지 저장할때 모든 데이터를 계속 저장하는문제
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java
Labels: enhancement

#245 Refactor/#215 camp 예약확인을 위한 캠핑지 조회시 반환 데이터 추가
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/dto/CampAddrDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampInfoDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSimpleDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
  src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/site/campingon/campingon/reservation/dto/CampAddrResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/CampResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
Labels: enhancement, feature

#246 Feat/#239 사용자의 예약목록에서 리뷰 유무 정보 반환
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/entity/Review.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
Labels: enhancement

#249 Feat/#247 캠프테이블 동물반입여부 컬럼 추가
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#250 Feat: #248 키워드 관련 서비스 로직 및 api 추가
  src/main/java/site/campingon/campingon/camp/repository/mongodb/MongoRecommendClient.java
  src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/user/controller/UserController.java
  src/main/java/site/campingon/campingon/user/controller/UserKeywordController.java
  src/main/java/site/campingon/campingon/user/dto/KeywordRequestDto.java
  src/main/java/site/campingon/campingon/user/dto/KeywordResponseDto.java
  src/main/java/site/campingon/campingon/user/entity/KeywordEnum.java
  src/main/java/site/campingon/campingon/user/repository/UserKeywordRepository.java
  src/main/java/site/campingon/campingon/user/service/UserService.java
Labels: feature

#255 Fix/#254 erd 변경
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: bug fix

#263 Refactor #256 S3경로 수정과 one + many를 분리 취소, 리뷰 formData에 필요한 필드 수정
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/s3bucket/controller/S3BucketController.java
  src/main/java/site/campingon/campingon/common/s3bucket/service/S3BucketService.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/entity/Review.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
  src/main/java/site/campingon/campingon/review/repository/ReviewRepository.java
  src/main/java/site/campingon/campingon/review/schedule/ReviewScheduler.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
Labels: enhancement, bug fix, subtask

#264 Fix: #257 회원 정보 업데이트 로직 변경
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/user/dto/UserUpdateRequestDto.java
  src/main/java/site/campingon/campingon/user/service/UserService.java
Labels: bug fix

#262 fix: #260 구글유저의 재가입 버그 해결
  src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
  src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
  src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
  src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
  src/main/java/site/campingon/campingon/user/controller/UserController.java
  src/main/java/site/campingon/campingon/user/repository/UserRepository.java
Labels: bug, bug fix

#269 Fix/#268 리뷰 추천 필드 반영 오류
  src/main/java/site/campingon/campingon/reservation/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewCreateRequestDto.java
  src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
  src/main/java/site/campingon/campingon/review/entity/Review.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
Labels: bug fix

#271 Improvement/#270 코드리뷰 피드백 반영
  src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/common/config/SecurityPath.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingProviderService.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
  src/test/java/site/campingon/campingon/common/public_data/service/GoCampingServiceTest.java
Labels: enhancement

#265 Feat: #258 Access Token Blacklist, RefreshToken Redis 저장
  .github/workflows/deploy.yml
  build.gradle
  docker-compose.yml
  src/main/java/site/campingon/campingon/common/config/RedisConfig.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/jwt/BlacklistService.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenParser.java
  src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshToken.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshTokenRepository.java
  src/main/java/site/campingon/campingon/common/jwt/RefreshTokenService.java
  src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/site/campingon/campingon/user/controller/UserAuthController.java
  src/main/java/site/campingon/campingon/user/controller/UserController.java
  src/main/java/site/campingon/campingon/user/service/UserAuthService.java
  src/main/java/site/campingon/campingon/user/service/UserService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/site/campingon/campingon/user/service/UserServiceTest.java
Labels: enhancement, feature

#273 Fix/#272 동물반입 여부 추가
  src/main/java/site/campingon/campingon/bookmark/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
Labels: enhancement

#280 Fix/#279 캠핑장 id로 리뷰 페이지를 조회하는 기능 추가
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/review/controller/ReviewController.java
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
  src/main/java/site/campingon/campingon/review/repository/ReviewRepository.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
Labels: enhancement

#277 Feat/#276 도시별 캠프이미지 불러오기 api 기능
  src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
  src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
  src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
Labels: feature

#281 Refactor/#278 reservation 필요한 주소만 반환, 예약 조회 쿼리 수정
  src/main/java/site/campingon/campingon/reservation/dto/CampAddrResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/CampResponseDto.java
  src/main/java/site/campingon/campingon/reservation/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
  src/main/resources/application-dev.yml
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement

#283 Refactor/#267 reservation 예약일자,시간 통합
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteReserveService.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/common/converter/CheckTimeConverter.java
  src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/entity/CheckTime.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
  src/main/java/site/campingon/campingon/reservation/utils/ReservationValidate.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement

#285 feat : #284 인덱스 추가
  src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
  src/main/java/site/campingon/campingon/camp/entity/Camp.java
  src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
  src/main/java/site/campingon/campingon/camp/entity/CampSite.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/user/entity/User.java
  src/main/java/site/campingon/campingon/user/entity/UserKeyword.java
Labels: enhancement

#286 Feat/#274 제주시로 검색, 자동완성 API 구현
  src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
  src/main/java/site/campingon/campingon/camp/repository/mongodb/MongoSearchClient.java
  src/main/java/site/campingon/campingon/camp/service/CampService.java
  src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java
  src/main/resources/application.yml
Labels: feature

#289 Refactor/#267 reservation 예약 날짜,시간 진짜 통합 성공
  src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
  src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteReserveService.java
  src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
  src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
Labels: enhancement

#288 Feat/#287 camp info 찜수, 추천수 연결
  src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
  src/main/java/site/campingon/campingon/bookmark/service/BookmarkService.java
  src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
  src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
  src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
  src/main/java/site/campingon/campingon/review/service/ReviewService.java
Labels: feature

#292 Fix/#291 나의예약 @Param 추가
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
Labels: enhancement

#295 Fix/#294 리뷰 상세 페이지에 캠핑장 이름 넣기
  src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java
Labels: enhancement

#298 Feat: #297 로그인시 반환되는 DTO 추가
  src/main/java/site/campingon/campingon/user/controller/UserAuthController.java
  src/main/java/site/campingon/campingon/user/dto/UserTokenResponseDto.java
Labels: enhancement

#300 Refactor/#205 reservation 예약상태 스케줄러로 관리
  src/main/java/site/campingon/campingon/common/oauth/TestController.java
  src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
  src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
  src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
  src/main/java/site/campingon/campingon/reservation/service/ReservationStatusUpdate.java
  src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationStatusUpdateTest.java
  src/test/java/site/campingon/campingon/review/service/ReviewServiceTest.java
Labels: enhancement, feature

#301 refactor: 스케줄러로 예약완료인 상태만 체크
  src/main/java/site/campingon/campingon/reservation/service/ReservationStatusUpdate.java
  src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java
Labels: enhancement, bug fix
